In [1]:
import numpy as np

# Simple learning network (Chapter 4-5-)

In [2]:
def neural_network(input_, weight):
    pred = wgt.dot(input_)
    return pred

In [31]:

out_len, inp_len = (1, 3)
wgt = np.zeros((out_len, inp_len))

data = np.array([
                [1, 0, 1],
                [0, 1, 1],
                [0, 0, 1],
                [1, 1, 1],
                [0, 1, 1],
                [1, 0, 1]])
labels = np.array([0,1,0,1,1,0])

α = 0.01
ϵ = 1e-10
for iteration in range(2000):
    total_error = np.zeros(out_len)
    for i, y in enumerate(labels):
        x = data[i]    
    
        pred = neural_network(x, wgt)
        Δ = pred - y
        
        error = np.zeros(out_len)

        for k in range(out_len):
            error[k] = (Δ[k] ** 2)
        
        total_error += error

        θs = np.outer(Δ,x)

        wgt = wgt - (α * θs)

        if iteration % 200 == 0:
            print("---------{}---------".format(iteration))
            print("Error: {}".format(str(error)))
            print("Prediction:" + str(pred))
            print("Label:" + str(y))
            print("Δ: " + str(Δ))
            print("θs: " + str(θs))
            print("wgt: " + str(wgt))
    if iteration % 200 == 0:
        print("\nIteration error: {}".format(total_error))
        #if error.all() < ϵ:
        #    break


---------0---------
Error: [0.]
Prediction:[0.]
Label:0
Δ: [0.]
θs: [[0. 0. 0.]]
wgt: [[0. 0. 0.]]
---------0---------
Error: [1.]
Prediction:[0.]
Label:1
Δ: [-1.]
θs: [[-0. -1. -1.]]
wgt: [[0.   0.01 0.01]]
---------0---------
Error: [0.0001]
Prediction:[0.01]
Label:0
Δ: [0.01]
θs: [[0.   0.   0.01]]
wgt: [[0.     0.01   0.0099]]
---------0---------
Error: [0.96059601]
Prediction:[0.0199]
Label:1
Δ: [-0.9801]
θs: [[-0.9801 -0.9801 -0.9801]]
wgt: [[0.009801 0.019801 0.019701]]
---------0---------
Error: [0.92255641]
Prediction:[0.039502]
Label:1
Δ: [-0.960498]
θs: [[-0.       -0.960498 -0.960498]]
wgt: [[0.009801   0.02940598 0.02930598]]
---------0---------
Error: [0.00152936]
Prediction:[0.03910698]
Label:0
Δ: [0.03910698]
θs: [[0.03910698 0.         0.03910698]]
wgt: [[0.00940993 0.02940598 0.02891491]]

Iteration error: [2.88478177]
---------200---------
Error: [0.00036753]
Prediction:[0.01917112]
Label:0
Δ: [0.01917112]
θs: [[0.01917112 0.         0.01917112]]
wgt: [[-0.07559451  

---------1600---------
Error: [1.46721658e-12]
Prediction:[1.21128716e-06]
Label:0
Δ: [1.21128716e-06]
θs: [[1.21128716e-06 0.00000000e+00 1.21128716e-06]]
wgt: [[-9.84134246e-06  9.99990170e-01  1.10284039e-05]]
---------1600---------
Error: [1.43728656e-12]
Prediction:[1.0000012]
Label:1
Δ: [1.19886887e-06]
θs: [[0.00000000e+00 1.19886887e-06 1.19886887e-06]]
wgt: [[-9.84134246e-06  9.99990158e-01  1.10164152e-05]]
---------1600---------
Error: [1.21361403e-10]
Prediction:[1.10164152e-05]
Label:0
Δ: [1.10164152e-05]
θs: [[0.00000000e+00 0.00000000e+00 1.10164152e-05]]
wgt: [[-9.84134246e-06  9.99990158e-01  1.09062510e-05]]
---------1600---------
Error: [7.70289729e-11]
Prediction:[0.99999122]
Label:1
Δ: [-8.77661512e-06]
θs: [[-8.77661512e-06 -8.77661512e-06 -8.77661512e-06]]
wgt: [[-9.75357630e-06  9.99990246e-01  1.09940172e-05]]
---------1600---------
Error: [1.53824398e-12]
Prediction:[1.00000124]
Label:1
Δ: [1.24025964e-06]
θs: [[0.00000000e+00 1.24025964e-06 1.24025964e-06]]
w

# Basic NN applied to MNIST dataset
Note: For now, it is a 2 layer NN, which is insuficient to have good results

In [38]:
from keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

n_train = 60000
images = x_train[0:60000]
labels = y_train[0:60000]

out_len, inp_len = (10, 784)
wgt = np.zeros((out_len,inp_len))

def toVec(x):
    """ Changes a (28,28) matrix into a (728,) vector
    """
    y = np.zeros(inp_len)
    for i in range(28):
        for j in range(28):
            y[i*28 + j] = x[i][j]
    return y

α = 0.001
ϵ = 1e-10

for iteration in range(10):
    total_error = np.zeros(out_len)
    
    for i, y in enumerate(labels):
        x = toVec(images[i]) / 255.0

        error = np.zeros(out_len)
        Δ = np.zeros(out_len)
    
        pred = neural_network(x, wgt)

        tmp = np.zeros(out_len)
        tmp[int(y)-1] = 1.0
        
        Δ = pred - tmp

        for k in range(out_len):
            error[k] = (Δ[k] ** 2)

        total_error += error
        
        θs = np.outer(Δ,x)

        wgt = wgt - (α * θs)

        if (i+iteration) % 10000 == 0:
            print("--------{}----------".format(iteration))
            print("Error: {}".format(str(error)))
            print("Prediction:" + str(pred))
            print("Label:" + str(tmp))
            print("Δ: " + str(Δ))
            #print("θs: " + str(θs))
            #print("wgt: " + str(wgt))
            
    if iteration % 1 == 0:
        print("\nIteration error: {}".format(total_error))
    
        #if error.all() < ϵ:
        #    break



--------0----------
Error: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Prediction:[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Label:[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Δ: [ 0.  0.  0.  0. -1.  0.  0.  0.  0.  0.]
--------0----------
Error: [6.86266380e-03 3.00607784e-02 9.67740854e-06 4.69047163e-03
 6.25284452e-04 4.47156272e-02 1.82521620e-02 9.62604181e-03
 2.39862591e-02 1.29983297e-03]
Prediction:[ 0.0828412  -0.17338044  1.00311085  0.06848702  0.02500569  0.2114607
  0.13510056 -0.09811239 -0.15487498  0.0360532 ]
Label:[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
Δ: [ 0.0828412  -0.17338044  0.00311085  0.06848702  0.02500569  0.2114607
  0.13510056 -0.09811239 -0.15487498  0.0360532 ]
--------0----------
Error: [0.00135889 0.05951062 0.00375868 0.02737645 0.01234666 0.0426919
 0.02022951 0.0037784  0.0542075  0.00746858]
Prediction:[ 0.03686309 -0.24394798 -0.06130811  0.16545829  0.88888448  0.20662019
 -0.14223048 -0.06146871  0.23282503  0.08642095]
Label:[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Δ: [ 0.03686309 -0.24394798

--------3----------
Error: [0.14286325 0.02124753 0.000381   0.00310871 0.00417765 0.06510098
 0.00030293 0.02121514 0.00559543 0.0109719 ]
Prediction:[ 0.37797255  0.14576533 -0.01951927  0.05575578  0.06463471  0.74485107
  0.01740499  0.14565418 -0.07480261 -0.10474683]
Label:[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
Δ: [ 0.37797255  0.14576533 -0.01951927  0.05575578  0.06463471 -0.25514893
  0.01740499  0.14565418 -0.07480261 -0.10474683]
--------3----------
Error: [1.00222479e-01 1.15264331e-05 9.14461489e-03 4.58417886e-05
 2.29255604e-02 2.35574334e-03 2.47081364e-03 1.67631662e-02
 1.43355178e-04 2.17513317e-02]
Prediction:[ 0.68342066 -0.00339506  0.09562748  0.00677066  0.15141189  0.048536
  0.04970728  0.12947265  0.0119731  -0.14748333]
Label:[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Δ: [-0.31657934 -0.00339506  0.09562748  0.00677066  0.15141189  0.048536
  0.04970728  0.12947265  0.0119731  -0.14748333]
--------3----------
Error: [9.25647828e-03 5.39337864e-03 1.18656970e-02 3.10418421e-02

--------5----------
Error: [0.00222303 0.00855218 0.07736528 0.01185017 0.01166821 0.00054169
 0.00041445 0.05814046 0.00105479 0.00853892]
Prediction:[-0.04714897  0.09247801  0.27814615  0.10885848 -0.1080195  -0.0232742
  0.02035795  0.75887667 -0.03247756 -0.09240628]
Label:[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
Δ: [-0.04714897  0.09247801  0.27814615  0.10885848 -0.1080195  -0.0232742
  0.02035795 -0.24112333 -0.03247756 -0.09240628]

Iteration error: [2034.5027238  2324.82330117 2706.57666056 2607.48240355 2967.66578622
 1662.22473931 2180.84299223 3051.64763949 3096.28008524 1644.40169359]
--------6----------
Error: [1.48211124e-02 4.34922101e-02 1.86654859e-04 7.10675643e-03
 7.66076108e-03 2.97449578e-02 2.57553416e-03 4.44133164e-02
 2.94058600e-04 2.30884302e-01]
Prediction:[-0.12174199  0.20854786  0.01366217 -0.08430158  0.08752577 -0.17246727
  0.05074972  0.21074467  0.01714814  0.51949578]
Label:[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
Δ: [-0.12174199  0.20854786  0.01366217 -0.0843015

--------8----------
Error: [0.01312677 0.00071069 0.00511795 0.13152637 0.35039349 0.01814988
 0.01810348 0.02568583 0.03402233 0.05272475]
Prediction:[-0.1145721   0.02665885  0.07153988  0.36266565  0.40805955  0.13472149
 -0.13454916 -0.16026799  0.18445142  0.2296187 ]
Label:[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Δ: [-0.1145721   0.02665885  0.07153988  0.36266565 -0.59194045  0.13472149
 -0.13454916 -0.16026799  0.18445142  0.2296187 ]
--------8----------
Error: [0.00068758 0.0034187  0.00850348 0.00760837 0.00533135 0.00055908
 0.04941017 0.01323378 0.44375454 0.01262339]
Prediction:[ 0.0262218  -0.05846968  0.09221432  0.08722599  0.07301609  0.02364495
  0.22228399  0.11503817  0.33385096 -0.11235386]
Label:[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
Δ: [ 0.0262218  -0.05846968  0.09221432  0.08722599  0.07301609  0.02364495
  0.22228399  0.11503817 -0.66614904 -0.11235386]

Iteration error: [2033.36335348 2319.24464813 2704.03134178 2604.01934327 2962.49508681
 1657.87515993 2176.62174902 3049.8

In [39]:
# Tests
n_test = 1000

pred_test = np.zeros(n_test)

bien_classé = 0

for i in range(n_test):
    x = toVec(x_test[i])
    y = y_test[i]
    
    pred = neural_network(x, wgt)
    
    tmp = max(pred)
    pred_test[i] = [i for i, j in enumerate(pred) if j == tmp][0] + 1
    
    if pred_test[i] == y:
        bien_classé += 1
    
    if i % 100 == 0:
        print("Prediction:" + str(pred_test[i]) + " Label:" + str(y))
            


Prediction:7.0 Label:7
Prediction:6.0 Label:6
Prediction:3.0 Label:3
Prediction:1.0 Label:4
Prediction:2.0 Label:2
Prediction:3.0 Label:3
Prediction:6.0 Label:6
Prediction:1.0 Label:1
Prediction:3.0 Label:8
Prediction:3.0 Label:1


In [40]:
print("Pourcentage bien classé: {}".format(str(bien_classé / n_test)))

Pourcentage bien classé: 0.691


In [46]:
# Export wgts as images
import matplotlib.pyplot as plt
import matplotlib.cm as cm

for i, weights in enumerate(wgt):
    plt.imsave('wgt{}.png'.format(i), np.array(weights).reshape(28,28), cmap=cm.gray)

# Brouillon NumPy, etc

In [18]:
X = np.zeros((3,3))
X[2] = np.array([1,2,3.])

In [19]:
X

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 2., 3.]])

In [20]:
X.dot(np.array([1,1,1]))

array([0., 0., 6.])

In [21]:
np.array([1,1,1]).dot(X)

array([1., 2., 3.])

In [16]:
np.outer(np.array([1,2,1]),np.array([3,1,4]))

array([[3, 1, 4],
       [6, 2, 8],
       [3, 1, 4]])

In [47]:
for i in range(3):
    X[i] = i

In [48]:
X

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.]])

In [33]:
len(x_test)

10000