In [2]:
import numpy as np

# Simple learning network (Chapter 4-5-)

In [3]:
def neural_network(input_, weight):
    pred = wgt.dot(input_)
    return pred

In [55]:
wgt = np.zeros((3,3))

data1 = np.array([8.5, 9.5, 10, 9])
data2 = np.array([0.65, 0.8, 0.8, 0.9])
data3 = np.array([1.2, 1.3, 0.5, 1.0])

x = np.array([data1[0], data2[0], data3[0]])
y = np.array([1.15, 1., 0.7])

α = 0.02
ϵ = 1e-10

error = np.array([0., 0, 0])
Δ = np.array([0., 0, 0])
              
for iteration in range(10000):
    pred = neural_network(x, wgt)
    
    Δ = pred - y
    
    for i in range(len(y)):
        error[i] = (Δ[i] ** 2)
        
    θs = np.outer(x,Δ)
    
    wgt = wgt - (α * θs)
    
    if iteration % 1000 == 0:
        print("------------------")
        print("Error: " + str(error))
        print("Prediction:" + str(pred))
        print("Δ: " + str(Δ))
        print("θs: " + str(θs))
        print("wgt: " + str(wgt))
    
    #if error.all() < ϵ:
    #    break

wgt

------------------
Error: [1.3225 1.     0.49  ]
Prediction:[0. 0. 0.]
Δ: [-1.15 -1.   -0.7 ]
θs: [[-9.775  -8.5    -5.95  ]
 [-0.7475 -0.65   -0.455 ]
 [-1.38   -1.2    -0.84  ]]
wgt: [[0.1955  0.17    0.119  ]
 [0.01495 0.013   0.0091 ]
 [0.0276  0.024   0.0168 ]]
------------------
Error: [0.02016074 0.81216302 0.26791144]
Prediction:[1.29198853 0.09879912 0.18239838]
Δ: [ 0.14198853 -0.90120088 -0.51760162]
θs: [[ 1.20690251 -7.66020745 -4.39961376]
 [ 0.09229255 -0.58578057 -0.33644105]
 [ 0.17038624 -1.08144105 -0.62112194]]
wgt: [[-24.0140095  153.36868457  88.10118689]
 [ -1.83636543  11.72819353   6.73714959]
 [ -3.39021311  21.65204959  12.43781462]]
------------------
Error: [0.02016074 0.81216302 0.26791144]
Prediction:[1.29198853 0.09879912 0.18239838]
Δ: [ 0.14198853 -0.90120088 -0.51760162]
θs: [[ 1.20690251 -7.66020745 -4.39961376]
 [ 0.09229255 -0.58578057 -0.33644105]
 [ 0.17038624 -1.08144105 -0.62112194]]
wgt: [[-48.15205976 306.57283367 176.09346215]
 [ -3.68221633

array([[-241.2323238 , 1532.0528223 ,  879.94367193],
       [ -18.4471777 ,  117.15698053,   67.28981021],
       [ -34.05632807,  216.28981021,  124.22734192]])

# Basic NN applied to MNIST dataset
Note: For now, it is a 2 layer NN, which is insuficient to have good results

In [36]:
from keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

n_train = 60000
images = x_train[0:60000]
labels = y_train[0:60000]

out_len = 10
inp_len = 784
wgt = np.zeros((out_len,inp_len))


def toVec(x):
    y = np.zeros(inp_len)
    for i in range(28):
        for j in range(28):
            y[i*28 + j] = x[i][j]
    return y


for i in range(60000):
    x = toVec(images[i]) / 255.0
    y = labels[i]
    
    α = 0.001
    ϵ = 1e-10

    error = np.zeros(out_len)
    Δ = np.zeros(out_len)

    for iteration in range(10):
        pred = neural_network(x, wgt)

        tmp = np.zeros(out_len)
        tmp[int(y)-1] = 1.0
        Δ = pred - tmp

        for k in range(out_len):
            error[k] = (Δ[k] ** 2)

        θs = np.outer(Δ,x)

        wgt = wgt - (α * θs)

        if iteration % 10 == 0 and i % 100 == 0:
            print("------------------")
            print("Error: " + str(error))
            print("Prediction:" + str(pred))
            print("Label:" + str(tmp))
            print("Δ: " + str(Δ))
            #print("θs: " + str(θs))
            #print("wgt: " + str(wgt))

        #if error.all() < ϵ:
        #    break



------------------
Error: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Prediction:[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Label:[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Δ: [ 0.  0.  0.  0. -1.  0.  0.  0.  0.  0.]
------------------
Error: [8.61280283e-03 2.47412092e-03 2.68933308e-03 1.21688106e-02
 8.53704236e-01 1.92611977e-02 6.00640396e-04 2.59982409e-02
 1.01583898e-03 1.20824414e-02]
Prediction:[ 0.09280519 -0.04974054  0.05185878  0.11031233  0.07603883  0.13878472
  0.02450797  0.1612397   0.03187223  0.10992016]
Label:[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Δ: [ 0.09280519 -0.04974054  0.05185878  0.11031233 -0.92396117  0.13878472
  0.02450797  0.1612397   0.03187223  0.10992016]
------------------
Error: [0.17017051 0.01002692 0.00933256 0.0028243  0.02021699 0.00171286
 0.00397669 0.0366292  0.01802176 0.00201172]
Prediction:[ 0.58748271  0.10013452  0.09660517 -0.05314414  0.14218645  0.0413867
 -0.06306099  0.19138757  0.13424515 -0.04485223]
Label:[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Δ: [-0.41251729  0.10013452 

------------------
Error: [2.58136768e-03 1.85391476e-01 1.59886608e-03 1.95138928e-02
 1.47572476e-09 6.10317712e-03 1.17519965e-03 8.91735562e-03
 1.88308623e-02 1.57443412e-03]
Prediction:[ 5.08071617e-02  5.69428896e-01  3.99858235e-02  1.39692136e-01
 -3.84151631e-05 -7.81228336e-02 -3.42811851e-02  9.44317511e-02
 -1.37225589e-01 -3.96791396e-02]
Label:[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
Δ: [ 5.08071617e-02 -4.30571104e-01  3.99858235e-02  1.39692136e-01
 -3.84151631e-05 -7.81228336e-02 -3.42811851e-02  9.44317511e-02
 -1.37225589e-01 -3.96791396e-02]
------------------
Error: [0.01544276 0.03186956 0.09604208 0.00472516 0.43183094 0.03143795
 0.05530825 0.04551371 0.07875283 0.06974454]
Prediction:[-0.12426891  0.17852049 -0.30990657  0.06873983  0.34286155  0.17730751
 -0.23517707  0.21333942  0.28062935  0.26409191]
Label:[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Δ: [-0.12426891  0.17852049 -0.30990657  0.06873983 -0.65713845  0.17730751
 -0.23517707  0.21333942  0.28062935  0.26409191]
---

------------------
Error: [0.0034693  0.00143906 0.20893226 0.23690204 0.37158983 0.13423856
 0.07581213 0.26621136 0.01484415 0.17921891]
Prediction:[ 0.05890081 -0.037935   -0.45709109  0.48672583 -0.60958169  0.63361419
  0.27534003  0.51595674 -0.12183658  0.42334255]
Label:[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
Δ: [ 0.05890081 -0.037935   -0.45709109  0.48672583 -0.60958169 -0.36638581
  0.27534003  0.51595674 -0.12183658  0.42334255]
------------------
Error: [3.10355639e-02 4.16633882e-03 7.51296654e-05 1.26200095e-04
 1.82733447e-03 9.24332175e-04 3.83578910e-02 2.31247743e-02
 8.83959449e-03 1.60204328e-03]
Prediction:[ 0.82383087  0.06454718  0.00866774 -0.01123388  0.04274733  0.03040283
  0.19585171 -0.15206832  0.09401912 -0.04002553]
Label:[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Δ: [-0.17616913  0.06454718  0.00866774 -0.01123388  0.04274733  0.03040283
  0.19585171 -0.15206832  0.09401912 -0.04002553]
------------------
Error: [2.19072371e-03 8.89627460e-03 5.49583659e-03 4.17591780e-0

------------------
Error: [2.83451624e-02 5.75733397e-04 2.49507872e-06 2.67447680e-02
 3.41493045e-03 2.02146033e-03 4.57219690e-03 4.10956412e-05
 1.81397032e-03 5.63747829e-03]
Prediction:[ 0.83163978  0.02399445 -0.00157958 -0.16353828  0.05843741  0.04496065
  0.06761802 -0.00641059 -0.04259073  0.07508314]
Label:[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Δ: [-0.16836022  0.02399445 -0.00157958 -0.16353828  0.05843741  0.04496065
  0.06761802 -0.00641059 -0.04259073  0.07508314]
------------------
Error: [9.59631461e-02 9.99420490e-02 1.44750731e-01 6.37773983e-03
 8.72124685e-02 6.97006116e-01 6.02622374e-04 2.65685342e-02
 1.56086396e-04 1.31358323e-01]
Prediction:[-0.30977919  0.31613612  0.38046121  0.07986075  0.29531757  0.16513108
  0.02454837  0.16299857  0.01249345 -0.36243389]
Label:[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
Δ: [-0.30977919  0.31613612  0.38046121  0.07986075  0.29531757 -0.83486892
  0.02454837  0.16299857  0.01249345 -0.36243389]
------------------
Error: [1.26328477e-01 9.

------------------
Error: [0.00111723 0.06999113 0.00333818 0.00258556 0.00121443 0.00733083
 0.0001329  0.01826372 0.00060915 0.0284555 ]
Prediction:[ 0.03342498  0.73544164  0.05777701 -0.05084837 -0.03484872  0.08562024
  0.01152829  0.13514332 -0.02468089  0.16868759]
Label:[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
Δ: [ 0.03342498 -0.26455836  0.05777701 -0.05084837 -0.03484872  0.08562024
  0.01152829  0.13514332 -0.02468089  0.16868759]
------------------
Error: [1.02078082e-03 1.94687594e-02 2.30201666e-01 2.59046127e-02
 1.50866622e-01 1.49984787e-04 5.14166226e-03 1.58375995e-02
 1.64516597e-02 4.09809102e-02]
Prediction:[-0.03194966 -0.1395305   0.52020664  0.1609491   0.38841553  0.01224683
 -0.07170539 -0.12584752  0.12826402  0.20243742]
Label:[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
Δ: [-0.03194966 -0.1395305  -0.47979336  0.1609491   0.38841553  0.01224683
 -0.07170539 -0.12584752  0.12826402  0.20243742]
------------------
Error: [1.12315846e-02 5.56425422e-02 1.02001241e-03 9.88875108e-0

------------------
Error: [0.00530278 0.05343286 0.08538464 0.00352705 0.06433365 0.00286429
 0.00580244 0.14490453 0.01407622 0.01137453]
Prediction:[ 0.07282018  0.23115549  0.70779349 -0.05938899  0.25364079  0.05351909
 -0.07617376 -0.38066327  0.11864325 -0.10665143]
Label:[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
Δ: [ 0.07282018  0.23115549 -0.29220651 -0.05938899  0.25364079  0.05351909
 -0.07617376 -0.38066327  0.11864325 -0.10665143]
------------------
Error: [0.00583044 0.03970037 0.01293328 0.01711825 0.04949982 0.02099906
 0.00183648 0.00123131 0.02268473 0.01167271]
Prediction:[ 0.07635731  0.19924951 -0.11372456 -0.13083672  0.22248555  0.85508948
  0.04285422 -0.03509    -0.15061452 -0.10804032]
Label:[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
Δ: [ 0.07635731  0.19924951 -0.11372456 -0.13083672  0.22248555 -0.14491052
  0.04285422 -0.03509    -0.15061452 -0.10804032]
------------------
Error: [0.03118042 0.00869763 0.00399171 0.0003645  0.0307393  0.03212135
 0.00140924 0.03852031 0.02167077

------------------
Error: [0.02343033 0.39080767 0.04827022 0.00502946 0.20580101 0.02532325
 0.0258196  0.02484518 0.16300054 0.00097086]
Prediction:[-0.15306968  0.62514612 -0.21970484  0.07091871 -0.45365296 -0.15913281
  0.16068479  0.15762353  0.59626675 -0.03115858]
Label:[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
Δ: [-0.15306968  0.62514612 -0.21970484  0.07091871 -0.45365296 -0.15913281
  0.16068479  0.15762353 -0.40373325 -0.03115858]
------------------
Error: [2.44865595e-02 1.33928001e-04 4.24560776e-04 2.71264336e-03
 1.60807834e-03 4.56220784e-04 1.41493874e-01 2.10573776e-02
 1.42243095e-04 3.50126784e-03]
Prediction:[-0.15648182 -0.01157273 -0.02060487 -0.05208304 -0.04010085 -0.02135933
  0.62384329  0.1451116  -0.01192657 -0.05917151]
Label:[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
Δ: [-0.15648182 -0.01157273 -0.02060487 -0.05208304 -0.04010085 -0.02135933
 -0.37615671  0.1451116  -0.01192657 -0.05917151]
------------------
Error: [6.96032355e-03 8.15604075e-03 6.38100477e-02 2.18931684e-0

------------------
Error: [0.00341693 0.00437461 0.12193585 0.012364   0.35714311 0.01001364
 0.0770362  0.00593706 0.0992613  0.04112745]
Prediction:[ 0.05845448 -0.06614084  0.34919314  0.11119351  0.40238548 -0.10006819
 -0.27755395 -0.07705231  0.31505761  0.20279904]
Label:[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Δ: [ 0.05845448 -0.06614084  0.34919314  0.11119351 -0.59761452 -0.10006819
 -0.27755395 -0.07705231  0.31505761  0.20279904]
------------------
Error: [6.92757120e-03 1.15575975e-03 9.07798744e-04 2.23626183e-04
 4.26525344e-01 1.37048789e-02 1.61464588e-04 1.34497855e-01
 1.56335336e-02 1.45924776e-02]
Prediction:[ 0.08323203  0.03399647  0.0301297  -0.01495414  0.34691092 -0.11706784
 -0.01270687  0.36673949 -0.12503413  0.12079933]
Label:[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Δ: [ 0.08323203  0.03399647  0.0301297  -0.01495414 -0.65308908 -0.11706784
 -0.01270687  0.36673949 -0.12503413  0.12079933]
------------------
Error: [0.02267433 0.00395047 0.00627795 0.31752376 0.00535348 0.0

------------------
Error: [1.75509586e-01 5.23450623e-02 1.42685061e-03 3.55281103e-04
 4.50167166e-02 3.84719023e-04 1.80945014e-02 4.86227579e-02
 1.07369201e-02 2.72371713e-05]
Prediction:[ 0.58106136 -0.22879043 -0.03777368  0.0188489   0.21217143  0.01961426
  0.1345158   0.22050569  0.10361911  0.00521892]
Label:[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Δ: [-0.41893864 -0.22879043 -0.03777368  0.0188489   0.21217143  0.01961426
  0.1345158   0.22050569  0.10361911  0.00521892]
------------------
Error: [6.07420573e-03 1.22015587e-04 7.77021365e-02 2.41008611e-01
 6.21003039e-04 1.61153153e-02 1.77389003e-03 2.44267454e-02
 4.03829927e-04 1.15290437e-03]
Prediction:[ 0.07793719 -0.01104607 -0.27875103  0.50907372  0.02491993  0.12694611
 -0.04211757  0.15629058 -0.02009552  0.03395445]
Label:[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
Δ: [ 0.07793719 -0.01104607 -0.27875103 -0.49092628  0.02491993  0.12694611
 -0.04211757  0.15629058 -0.02009552  0.03395445]
------------------
Error: [1.11097520e-03 4.

------------------
Error: [3.78030778e-04 5.65453705e-02 3.30868627e-02 2.52780073e-02
 7.39072850e-05 2.87912672e-03 1.55041951e-03 3.98430505e-04
 1.74974112e-02 5.83907577e-02]
Prediction:[-0.01944301  0.2377927   0.18189795  0.84100941 -0.00859693  0.05365749
 -0.03937537  0.01996072  0.13227778  0.2416418 ]
Label:[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
Δ: [-0.01944301  0.2377927   0.18189795 -0.15899059 -0.00859693  0.05365749
 -0.03937537  0.01996072  0.13227778  0.2416418 ]
------------------
Error: [1.03042142e-01 4.17061942e-03 6.36162702e-01 2.20325355e-02
 6.10660486e-01 2.48650440e-03 4.28289560e-04 2.76429201e-02
 5.37620930e-03 2.18062824e-04]
Prediction:[-0.32100178 -0.06458033  0.79759808  0.14843361  0.21855231 -0.04986486
  0.02069516  0.1662616   0.07332264 -0.01476695]
Label:[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Δ: [-0.32100178 -0.06458033  0.79759808  0.14843361 -0.78144769 -0.04986486
  0.02069516  0.1662616   0.07332264 -0.01476695]
------------------
Error: [7.01214792e-03 6.

------------------
Error: [3.42888763e-02 3.99422153e-02 1.56061112e-02 1.51474436e-01
 4.23168675e-02 6.61835334e-05 3.39421935e-02 2.53191073e-02
 3.07057733e-01 2.36035266e-01]
Prediction:[ 0.18517256  0.19985549 -0.12492442  0.38919717 -0.20571064  0.00813533
  0.18423407  0.15911979  0.4458721   0.48583461]
Label:[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
Δ: [ 0.18517256  0.19985549 -0.12492442  0.38919717 -0.20571064  0.00813533
  0.18423407  0.15911979 -0.5541279   0.48583461]
------------------
Error: [0.02888853 0.02329562 0.03445532 0.0009941  0.00192368 0.0003239
 0.00219472 0.00514389 0.00521301 0.02046556]
Prediction:[ 0.83003373  0.15262904 -0.18562145  0.03152941  0.04385982  0.01799735
 -0.04684779  0.07172092  0.0722012  -0.1430579 ]
Label:[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Δ: [-0.16996627  0.15262904 -0.18562145  0.03152941  0.04385982  0.01799735
 -0.04684779  0.07172092  0.0722012  -0.1430579 ]
------------------
Error: [0.03344527 0.00579679 0.06195518 0.01914995 0.0129624  0.00

------------------
Error: [1.11397357e-04 1.80805042e-02 1.60910186e-02 6.11234376e-02
 2.98994968e-01 2.10005522e-03 1.92211186e-02 1.10090098e-01
 8.55218174e-04 8.15709916e-02]
Prediction:[-0.01055449 -0.13446377  0.12685038  0.24723155 -0.54680432 -0.04582636
 -0.13864025  0.33179828  0.97075589  0.28560636]
Label:[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
Δ: [-0.01055449 -0.13446377  0.12685038  0.24723155 -0.54680432 -0.04582636
 -0.13864025  0.33179828 -0.02924411  0.28560636]
------------------
Error: [5.13141012e-05 6.55586321e-02 4.40665863e-02 2.62115376e-03
 1.67168764e-02 1.23126354e-02 4.26823112e-02 5.96878643e-04
 2.65869102e-02 1.39398988e-02]
Prediction:[-0.00716339  0.2560442  -0.20992043 -0.0511972   0.12929376 -0.11096232
  1.20659698  0.0244311   0.16305493 -0.11806735]
Label:[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
Δ: [-0.00716339  0.2560442  -0.20992043 -0.0511972   0.12929376 -0.11096232
  0.20659698  0.0244311   0.16305493 -0.11806735]
------------------
Error: [2.43924727e-03 3.

------------------
Error: [0.09649828 0.0005535  0.01717445 0.01462445 0.00516268 0.00665917
 0.01392409 0.20048233 0.00083226 0.00028547]
Prediction:[ 0.31064172  0.02352656  0.13105133 -0.12093161 -0.07185181  0.08160371
 -0.11800038  0.55224746  0.02884894  0.01689598]
Label:[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
Δ: [ 0.31064172  0.02352656  0.13105133 -0.12093161 -0.07185181  0.08160371
 -0.11800038 -0.44775254  0.02884894  0.01689598]
------------------
Error: [0.00407512 0.00783948 0.03179079 0.00244239 0.15339542 0.0041438
 0.04545656 0.43688251 0.02466089 0.08253483]
Prediction:[-0.06383665 -0.08854086 -0.17829973 -0.0494205   0.39165728  0.06437239
 -0.21320545  0.33902911  0.15703786  0.28728875]
Label:[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
Δ: [-0.06383665 -0.08854086 -0.17829973 -0.0494205   0.39165728  0.06437239
 -0.21320545 -0.66097089  0.15703786  0.28728875]
------------------
Error: [1.21420295e-05 1.94340133e-03 1.07527810e-03 1.01091333e-02
 9.59217659e-03 5.83228840e-02 1.3322100

------------------
Error: [0.00488468 0.00119892 0.00534597 0.0262244  0.09008384 0.0037302
 0.53167829 0.00134878 0.08938431 0.12026606]
Prediction:[-0.06989047 -0.03462539  0.07311611 -0.16193951  0.3001397   0.06107537
  0.27083727 -0.03672576  0.29897209 -0.34679398]
Label:[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
Δ: [-0.06989047 -0.03462539  0.07311611 -0.16193951  0.3001397   0.06107537
 -0.72916273 -0.03672576  0.29897209 -0.34679398]
------------------
Error: [7.34089536e-03 7.09369211e-03 2.14010217e-01 8.79086482e-05
 1.06478300e-02 4.00505896e-02 3.49069754e-02 2.80277080e-01
 2.40139555e-02 2.46216428e-02]
Prediction:[ 0.08567903  0.08422406  0.46261238 -0.00937596  0.10318832 -0.20012643
  0.18683409  0.47058799 -0.15496437  0.15691285]
Label:[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
Δ: [ 0.08567903  0.08422406  0.46261238 -0.00937596  0.10318832 -0.20012643
  0.18683409 -0.52941201 -0.15496437  0.15691285]
------------------
Error: [0.00372058 0.01679344 0.04667502 0.01265491 0.0003348  0.02

------------------
Error: [2.09558411e-02 2.18656728e-02 1.05792589e-01 1.92017168e-02
 5.14453572e-01 5.95345468e-03 4.64514917e-02 5.65836072e-06
 2.51449778e-02 4.17689078e-02]
Prediction:[ 0.14476132 -0.14787046  0.32525773 -0.13857026  0.28274581 -0.07715863
  0.21552608 -0.00237873  0.15857168  0.20437443]
Label:[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Δ: [ 0.14476132 -0.14787046  0.32525773 -0.13857026 -0.71725419 -0.07715863
  0.21552608 -0.00237873  0.15857168  0.20437443]
------------------
Error: [0.19126686 0.16263984 0.00234227 0.07273056 0.0379877  0.01203995
 0.13826795 0.12102043 0.00139081 0.1945992 ]
Prediction:[ 0.43734066 -0.4032863   0.04839696 -0.26968604  0.19490432  0.10972673
  0.37184399  0.3478799  -0.0372935   0.55886601]
Label:[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
Δ: [ 0.43734066 -0.4032863   0.04839696 -0.26968604  0.19490432  0.10972673
  0.37184399  0.3478799  -0.0372935  -0.44113399]
------------------
Error: [0.02741193 0.00438385 0.00021228 0.00011925 0.00140564 0.0

------------------
Error: [0.0004419  0.00268373 0.26496128 0.03790758 0.06041355 0.00879733
 0.13138347 0.25052359 0.10751942 0.08300896]
Prediction:[-0.02102135  0.05180471  0.4852561  -0.19469869  0.24579168 -0.09379409
  0.36246858  0.50052331 -0.32790154  0.28811276]
Label:[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
Δ: [-0.02102135  0.05180471 -0.5147439  -0.19469869  0.24579168 -0.09379409
  0.36246858  0.50052331 -0.32790154  0.28811276]
------------------
Error: [1.12870273e-02 1.60243332e-01 1.95312189e-02 2.88197499e-02
 9.76905123e-04 2.58982349e-03 1.65173151e-02 6.65111418e-02
 6.58133911e-05 1.16282135e-02]
Prediction:[ 0.10624042  0.59969595  0.13975414  0.16976381  0.03125548  0.05089031
  0.12851971 -0.25789754 -0.00811255 -0.10783419]
Label:[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
Δ: [ 0.10624042 -0.40030405  0.13975414  0.16976381  0.03125548  0.05089031
  0.12851971 -0.25789754 -0.00811255 -0.10783419]
------------------
Error: [2.64400522e-03 1.44893972e-02 4.65250655e-03 2.04691823e-0

------------------
Error: [3.14135043e-04 1.51047297e-02 7.66907658e-02 2.19710437e-02
 2.25644050e-02 1.59449921e-02 3.01311967e-02 1.85011933e-02
 1.40133296e-02 3.82524201e-01]
Prediction:[ 0.01772386  0.1229013   0.27693098  0.14822633  0.15021453  0.12627348
  0.1735834  -0.13601909 -0.11837791  0.38151459]
Label:[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
Δ: [ 0.01772386  0.1229013   0.27693098  0.14822633  0.15021453  0.12627348
  0.1735834  -0.13601909 -0.11837791 -0.61848541]
------------------
Error: [1.00420025e-02 2.14452300e-01 4.28980051e-02 5.30229603e-03
 9.43021234e-01 8.79091673e-04 2.76451100e-02 5.20095067e-02
 2.60794182e-02 9.55381353e-03]
Prediction:[ 0.10020979  0.46308995  0.20711834  0.07281687  0.0289072   0.02964948
  0.16626819 -0.22805593  0.16149123 -0.09774361]
Label:[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Δ: [ 0.10020979  0.46308995  0.20711834  0.07281687 -0.9710928   0.02964948
  0.16626819 -0.22805593  0.16149123 -0.09774361]
------------------
Error: [0.02552209 0.0545

------------------
Error: [0.08287016 0.00548972 0.00049119 0.00425072 0.02232238 0.08806548
 0.01776727 0.0645363  0.0056852  0.00076877]
Prediction:[ 0.28787177 -0.07409268 -0.02216286  0.06519751  0.14940677  0.29675829
  0.86670608 -0.25403995 -0.07540027  0.02772678]
Label:[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
Δ: [ 0.28787177 -0.07409268 -0.02216286  0.06519751  0.14940677  0.29675829
 -0.13329392 -0.25403995 -0.07540027  0.02772678]
------------------
Error: [1.75105482e-03 4.18231534e-03 1.66337520e-03 9.31655482e-04
 1.43739659e-02 9.15617078e-03 1.68408005e-03 8.74544721e-03
 2.56479208e-05 1.34234220e-02]
Prediction:[-0.04184561  0.06467082 -0.0407845  -0.03052303  0.11989148  0.09568788
 -0.04103754 -0.0935171  -0.00506438  0.88414051]
Label:[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
Δ: [-0.04184561  0.06467082 -0.0407845  -0.03052303  0.11989148  0.09568788
 -0.04103754 -0.0935171  -0.00506438 -0.11585949]
------------------
Error: [0.16228887 0.0193055  0.10469192 0.00588122 0.01826167 0.0

------------------
Error: [5.50377728e-03 1.04493822e-01 4.46738297e-04 1.60469217e-02
 7.20866275e-01 1.09897171e-03 3.17171471e-02 1.24530320e-01
 7.82162701e-02 1.60935880e-04]
Prediction:[ 0.07418745  0.32325504 -0.02113618  0.12667645  0.15096156 -0.03315074
 -0.17809309  0.35288854  0.27967172 -0.01268605]
Label:[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Δ: [ 0.07418745  0.32325504 -0.02113618  0.12667645 -0.84903844 -0.03315074
 -0.17809309  0.35288854  0.27967172 -0.01268605]
------------------
Error: [2.72692473e-02 1.62262121e-03 5.97881711e-01 2.86710204e-03
 5.94385367e-02 8.59342544e-03 9.96277331e-06 4.08042582e-01
 1.00558232e-02 2.02394572e-02]
Prediction:[ 0.16513403 -0.04028177  0.77322811  0.05354533  0.2438002   0.09270073
 -0.00315639  0.36121789 -0.10027873 -0.14226545]
Label:[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
Δ: [ 0.16513403 -0.04028177  0.77322811  0.05354533  0.2438002   0.09270073
 -0.00315639 -0.63878211 -0.10027873 -0.14226545]
------------------
Error: [1.52327114e-02 4.

------------------
Error: [0.00115313 0.05682857 0.07549347 0.0038607  0.38157444 0.00681211
 0.03016489 0.02271022 0.00104901 0.01001519]
Prediction:[ 0.03395779 -0.23838744  0.27476075 -0.06213457  0.38228288  0.08253552
  0.17368043  0.15069911  0.03238845 -0.1000759 ]
Label:[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Δ: [ 0.03395779 -0.23838744  0.27476075 -0.06213457 -0.61771712  0.08253552
  0.17368043  0.15069911  0.03238845 -0.1000759 ]
------------------
Error: [8.17491129e-04 1.65488824e-02 1.05861532e-01 1.48903635e-03
 8.43959616e-01 6.64390879e-03 3.37439490e-02 2.70325783e-02
 1.59689410e-04 3.57765214e-02]
Prediction:[ 0.0285918   0.12864246  0.32536369 -0.03858803  0.08132725  0.08151018
  0.18369526 -0.16441587 -0.01263683  0.18914683]
Label:[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Δ: [ 0.0285918   0.12864246  0.32536369 -0.03858803 -0.91867275  0.08151018
  0.18369526 -0.16441587 -0.01263683  0.18914683]
------------------
Error: [1.65990474e-01 2.46976613e-02 3.11222173e-02 8.97505750e-0

------------------
Error: [0.00930458 0.07569193 0.12323344 0.01068966 0.01080528 0.00022803
 0.01231481 0.00044539 0.10278457 0.00378794]
Prediction:[-0.09646024  0.27512167  0.64895379  0.10339082  0.10394846 -0.0151006
 -0.1109721  -0.02110417  0.32060033 -0.06154621]
Label:[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
Δ: [-0.09646024  0.27512167 -0.35104621  0.10339082  0.10394846 -0.0151006
 -0.1109721  -0.02110417  0.32060033 -0.06154621]
------------------
Error: [0.01219081 0.01173816 0.04218729 0.0304546  0.01026721 0.01596771
 0.00275887 0.01112139 0.15048713 0.0374508 ]
Prediction:[-0.110412   -0.10834279  0.20539545  0.17451246  0.10132723  0.12636342
  0.05252493 -0.10545798  0.6120733  -0.19352209]
Label:[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
Δ: [-0.110412   -0.10834279  0.20539545  0.17451246  0.10132723  0.12636342
  0.05252493 -0.10545798 -0.3879267  -0.19352209]
------------------
Error: [5.74879448e-03 6.10135625e-02 2.33290393e-01 1.66345898e-04
 7.16412950e-02 1.69246418e-02 2.26502795

------------------
Error: [1.04552034e-02 1.09315604e-02 1.31687024e-02 2.40542703e-02
 3.09449569e-01 1.69834384e-03 3.60135845e-03 7.32292644e-05
 2.37008921e-02 2.01158990e-02]
Prediction:[ 0.10225069 -0.1045541   0.11475497  0.15509439  0.44371808  0.04121097
  0.06001132 -0.00855741  0.15395094  0.14183053]
Label:[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Δ: [ 0.10225069 -0.1045541   0.11475497  0.15509439 -0.55628192  0.04121097
  0.06001132 -0.00855741  0.15395094  0.14183053]
------------------
Error: [1.14288536e-02 5.46205442e-03 8.86913576e-03 1.75829005e-02
 5.61496767e-02 5.28390598e-03 6.30793610e-02 2.79648872e-02
 9.09877110e-06 1.92642871e-01]
Prediction:[-0.10690582 -0.07390571 -0.09417609  0.13260053  0.23695923  0.07269048
 -0.25115605  0.16722705 -0.00301642  0.56108899]
Label:[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
Δ: [-0.10690582 -0.07390571 -0.09417609  0.13260053  0.23695923  0.07269048
 -0.25115605  0.16722705 -0.00301642 -0.43891101]
------------------
Error: [0.01145126 0.0430

------------------
Error: [0.00513151 0.03787406 0.04865726 0.12267862 0.00012745 0.00617741
 0.00314067 0.00219877 0.05372589 0.06257466]
Prediction:[-0.07163457  0.19461258  0.2205839   0.35025508  0.01128932  0.07859653
  0.94395833  0.046891   -0.23178847 -0.25014928]
Label:[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
Δ: [-0.07163457  0.19461258  0.2205839   0.35025508  0.01128932  0.07859653
 -0.05604167  0.046891   -0.23178847 -0.25014928]
------------------
Error: [6.02824088e-03 2.17499556e-02 2.13252834e-01 3.15707161e-03
 7.68584623e-02 1.21176467e-04 6.32582415e-02 2.52093170e-01
 1.64059980e-01 1.27526064e-02]
Prediction:[ 0.07764175  0.14747866  0.46179306 -0.05618782 -0.27723359 -0.01100802
 -0.25151191  0.49791119  0.40504318  0.11292744]
Label:[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
Δ: [ 0.07764175  0.14747866  0.46179306 -0.05618782 -0.27723359 -0.01100802
 -0.25151191 -0.50208881  0.40504318  0.11292744]
------------------
Error: [0.00215312 0.17790073 0.06288672 0.00207917 0.03798535 0.0

------------------
Error: [2.79610462e-05 5.14255483e-02 7.18160309e-03 3.20383049e-02
 1.64604047e-02 2.29542107e-04 2.03516329e-04 1.29961259e-02
 1.00359576e-02 1.92930714e-05]
Prediction:[-0.00528782  0.22677202 -0.08474434 -0.17899247  0.12829811  0.01515065
 -0.01426591 -0.11400055  0.10017963  1.00439239]
Label:[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
Δ: [-0.00528782  0.22677202 -0.08474434 -0.17899247  0.12829811  0.01515065
 -0.01426591 -0.11400055  0.10017963  0.00439239]
------------------
Error: [1.05791309e-01 4.70636316e-04 5.75823079e-01 6.44651198e-03
 2.00067437e-01 9.15725097e-03 2.57669525e-04 1.03183651e-05
 4.58181229e-02 9.29313521e-04]
Prediction:[ 0.32525576  0.02169415  0.24116993  0.08029017  0.44728899  0.09569353
 -0.01605209  0.00321222  0.21405168  0.03048464]
Label:[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
Δ: [ 0.32525576  0.02169415 -0.75883007  0.08029017  0.44728899  0.09569353
 -0.01605209  0.00321222  0.21405168  0.03048464]
------------------
Error: [0.0084093  0.0191

------------------
Error: [0.00861614 0.02467996 0.13033504 0.00935408 0.05118263 0.00087327
 0.01046782 0.00221426 0.13643978 0.10195275]
Prediction:[ 0.09282314  0.15709858 -0.36101945  0.0967165  -0.22623577  0.0295511
  0.10231235 -0.04705597  0.63062244  0.3193004 ]
Label:[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
Δ: [ 0.09282314  0.15709858 -0.36101945  0.0967165  -0.22623577  0.0295511
  0.10231235 -0.04705597 -0.36937756  0.3193004 ]
------------------
Error: [0.0984816  0.00033971 0.05021991 0.00630598 0.02100606 0.00953252
 0.00108203 0.00739653 0.00403184 0.01141075]
Prediction:[ 0.31381778  0.01843117  0.775902   -0.07941023  0.14493468  0.09763465
  0.03289428 -0.08600306 -0.06349676 -0.1068211 ]
Label:[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
Δ: [ 0.31381778  0.01843117 -0.224098   -0.07941023  0.14493468  0.09763465
  0.03289428 -0.08600306 -0.06349676 -0.1068211 ]
------------------
Error: [9.42041035e-03 4.06115059e-03 1.48375954e-02 1.27769745e-02
 3.53869847e-03 1.65887370e-04 5.84788543

------------------
Error: [9.56233636e-04 6.82253243e-03 8.76380136e-02 7.82648204e-04
 8.30966836e-01 1.13562581e-02 1.06303938e-02 1.42261226e-01
 1.73185251e-03 5.62861213e-06]
Prediction:[-0.03092303  0.08259862  0.29603718 -0.02797585  0.08842618  0.10656575
 -0.1031038   0.37717533 -0.04161553  0.00237247]
Label:[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Δ: [-0.03092303  0.08259862  0.29603718 -0.02797585 -0.91157382  0.10656575
 -0.1031038   0.37717533 -0.04161553  0.00237247]
------------------
Error: [1.75522527e-01 2.76194800e-04 5.28465796e-03 3.52318794e-01
 1.65132399e-04 2.40413823e-02 7.42534791e-03 6.05517183e-03
 3.86513709e-02 1.90413274e-02]
Prediction:[ 0.58104591  0.01661911  0.07269565  0.59356448  0.01285039  0.15505284
  0.08617046  0.07781498 -0.19659952 -0.13799032]
Label:[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Δ: [-0.41895409  0.01661911  0.07269565  0.59356448  0.01285039  0.15505284
  0.08617046  0.07781498 -0.19659952 -0.13799032]
------------------
Error: [0.15112347 0.0007

------------------
Error: [0.00289783 0.0149917  0.00535721 0.00625991 0.00196454 0.00276731
 0.00848112 0.00470415 0.01323759 0.02522856]
Prediction:[ 0.05383153 -0.12244061  0.07319296 -0.0791196   0.95567687 -0.05260521
 -0.09209299 -0.06858681  0.11505474  0.15883501]
Label:[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Δ: [ 0.05383153 -0.12244061  0.07319296 -0.0791196  -0.04432313 -0.05260521
 -0.09209299 -0.06858681  0.11505474  0.15883501]
------------------
Error: [0.04831545 0.0702938  0.02303139 0.0031955  0.02105369 0.042665
 0.00330313 0.02378643 0.00121347 0.0132538 ]
Prediction:[-0.21980777  0.26512979 -0.15176098  0.05652873 -0.1450989  -0.20655507
  0.05747282  0.84577149 -0.03483485  0.11512514]
Label:[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
Δ: [-0.21980777  0.26512979 -0.15176098  0.05652873 -0.1450989  -0.20655507
  0.05747282 -0.15422851 -0.03483485  0.11512514]
------------------
Error: [0.00712987 0.05745349 0.02065975 0.0295497  0.04849961 0.02285873
 0.06372176 0.04211133 0.0036685  0

------------------
Error: [0.0146174  0.10297607 0.00196428 0.0053491  0.14677778 0.07679099
 0.02891393 0.21145788 0.65230063 0.01327165]
Prediction:[ 0.12090243  0.32089884 -0.0443202   0.07313755  0.38311589  0.27711187
  0.17004097 -0.4598455   0.19234869  0.11520267]
Label:[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
Δ: [ 0.12090243  0.32089884 -0.0443202   0.07313755  0.38311589  0.27711187
  0.17004097 -0.4598455  -0.80765131  0.11520267]
------------------
Error: [1.10775526e-03 2.01675671e-02 5.06533311e-04 1.20052625e-02
 1.68454545e-04 1.10755774e-02 2.56553597e-03 3.19877949e-01
 3.96305570e-03 4.62382053e-03]
Prediction:[ 0.03328296  0.14201256  0.02250629  0.10956853 -0.012979   -0.10524057
  0.05065112  0.43442246 -0.06295281  0.06799868]
Label:[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
Δ: [ 0.03328296  0.14201256  0.02250629  0.10956853 -0.012979   -0.10524057
  0.05065112 -0.56557754 -0.06295281  0.06799868]
------------------
Error: [1.49199006e-06 5.56254173e-03 2.52376627e-02 1.26810593e-0

------------------
Error: [5.32860881e-04 1.30811451e-04 1.68337142e-02 8.24984419e-04
 1.72550722e-01 1.01119075e-01 1.40284727e-03 5.67410445e-03
 7.56011701e-02 1.95842177e-01]
Prediction:[-0.02308378 -0.01143728 -0.1297448  -0.02872254  0.41539225 -0.31799226
 -0.0374546   0.07532665  0.27495667  0.55745941]
Label:[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
Δ: [-0.02308378 -0.01143728 -0.1297448  -0.02872254  0.41539225 -0.31799226
 -0.0374546   0.07532665  0.27495667 -0.44254059]
------------------
Error: [1.90525827e-02 1.15660335e-02 3.28421584e-02 1.19540902e-01
 1.28566825e-02 1.49126411e-02 1.14645063e-02 4.69619035e-03
 5.11902958e-05 1.47770984e-02]
Prediction:[ 0.13803109  0.10754549  0.81877594 -0.34574688  0.11338731  0.12211732
  0.10707243 -0.06852876  0.00715474  0.12156109]
Label:[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
Δ: [ 0.13803109  0.10754549 -0.18122406 -0.34574688  0.11338731  0.12211732
  0.10707243 -0.06852876  0.00715474  0.12156109]
------------------
Error: [0.0067876  0.0034

------------------
Error: [0.04922799 0.03962997 0.08479621 0.00057269 0.01431893 0.00503898
 0.00112774 0.07554817 0.1473777  0.0287858 ]
Prediction:[-0.22187382  0.19907278  0.29119788 -0.02393086  0.11966174 -0.07098575
  1.03358188 -0.27486028  0.38389804 -0.1696638 ]
Label:[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
Δ: [-0.22187382  0.19907278  0.29119788 -0.02393086  0.11966174 -0.07098575
  0.03358188 -0.27486028  0.38389804 -0.1696638 ]
------------------
Error: [2.61114177e-01 2.84039453e-02 1.77360782e-02 1.46745688e-02
 1.11283406e-03 1.14704319e-02 3.61721874e-05 3.79106485e-01
 6.49008530e-03 7.68199473e-03]
Prediction:[ 0.51099332  0.1685347  -0.13317687  0.12113863  0.03335917 -0.1071001
  0.00601433  0.38428376  0.08056107 -0.08764699]
Label:[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
Δ: [ 0.51099332  0.1685347  -0.13317687  0.12113863  0.03335917 -0.1071001
  0.00601433 -0.61571624  0.08056107 -0.08764699]
------------------
Error: [0.00161613 0.02841917 0.04268589 0.04761977 0.02704392 0.002

------------------
Error: [0.00705028 0.00351411 0.00213689 0.1765233  0.02315162 0.00061911
 0.04232386 0.00493792 0.01282699 0.03215759]
Prediction:[-0.08396592  0.05927989  0.04622647  0.57985324 -0.15215657  0.02488192
  0.20572765  0.07027033 -0.11325632  0.17932537]
Label:[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
Δ: [-0.08396592  0.05927989  0.04622647 -0.42014676 -0.15215657  0.02488192
  0.20572765  0.07027033 -0.11325632  0.17932537]
------------------
Error: [0.00124156 0.02197584 0.05019378 0.26856846 0.05060695 0.03084587
 0.0438218  0.01334039 0.230108   0.0355668 ]
Prediction:[-0.03523576 -0.14824252 -0.22403969  0.48176409  0.22495988  0.17562993
 -0.20933658  0.11550063  0.47969574 -0.18859163]
Label:[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
Δ: [-0.03523576 -0.14824252 -0.22403969 -0.51823591  0.22495988  0.17562993
 -0.20933658  0.11550063  0.47969574 -0.18859163]
------------------
Error: [0.00153087 0.01053238 0.01677523 0.05329759 0.01283606 0.0027264
 0.00851558 0.00271328 0.14646496 

In [51]:
# Tests
n_test = 1000

pred_test = np.zeros(n_test)

bien_classé = 0

for i in range(n_test):
    x = toVec(x_test[i])
    y = y_test[i]
    
    pred = neural_network(x, wgt)
    
    tmp = max(pred)
    pred_test[i] = [i for i, j in enumerate(pred) if j == tmp][0] + 1
    
    if pred_test[i] == y:
        bien_classé += 1
    
    if i % 100 == 0:
        print("Prediction:" + str(pred_test[i]) + " Label:" + str(y))
            


Prediction:7.0 Label:7
Prediction:6.0 Label:6
Prediction:3.0 Label:3
Prediction:1.0 Label:4
Prediction:2.0 Label:2
Prediction:3.0 Label:3
Prediction:6.0 Label:6
Prediction:8.0 Label:1
Prediction:3.0 Label:8
Prediction:3.0 Label:1


In [47]:
print("Pourcentage bien classé: " + str(bien_classé / n_test))

Pourcentage bien classé: 0.633


# Brouillon NumPy, etc

In [18]:
X = np.zeros((3,3))
X[2] = np.array([1,2,3.])

In [19]:
X

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 2., 3.]])

In [20]:
X.dot(np.array([1,1,1]))

array([0., 0., 6.])

In [21]:
np.array([1,1,1]).dot(X)

array([1., 2., 3.])

In [16]:
np.outer(np.array([1,2,1]),np.array([3,1,4]))

array([[3, 1, 4],
       [6, 2, 8],
       [3, 1, 4]])

In [47]:
for i in range(3):
    X[i] = i

In [48]:
X

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.]])

In [33]:
len(x_test)

10000