In [2]:
import numpy as np

# Simple stupid network (Chapter 1-3)

In [3]:
ih_wgt = np.array([
            [0.1, 0.2, -0.1],
            [-0.1, 0.1, 0.9],
            [0.1, 0.4, 0.1]]).T
ho_wgt = np.array([
            [0.3, 1.1, -0.3],
            [0.1, 0.2, 0.0],
            [0.0, 1.3, 0.1]]).T
weights = [ih_wgt, ho_wgt]

In [4]:
def neural_network(input_, weights):
    hid = input_.dot(weights[0])
    pred = hid.dot(weights[1])
    return pred


def sigma(x):
    return x


#def w_sum(a, b):
#    assert(len(a) == len(b))
#    
#    output = 0
#    
#    for i in range(len(a)):
#        output += (a[i] * b[i])
#        
#    return output


#def ele_mul(a, vec):
#    output = [0] * len(vec)
#    
#    for i in range(len(vec)):
#        output[i] = a*vec[i]
#        
#    return output


#def vect_mat_mul(input_, weights):
#    output = [0] * len(weights)
#    
#    for i in range(len(weights)):
#        output[i] = w_sum(input_, weights[i])
#    
#    return output



In [3]:
data1 = np.array([8.5, 9.5, 10, 9])
data2 = np.array([0.65, 0.8, 0.8, 0.9])
data3 = np.array([1.2, 1.3, 0.5, 1.0])

input_ = np.array([data1[0], data2[0], data3[0]])
pred = neural_network(input_, weights)

NameError: name 'weights' is not defined

In [6]:
pred

array([0.2135, 0.145 , 0.5065])

# Simple learning network (Chapter 4-5-)

In [1]:
def neural_network(input_, weight):
    pred = wgt.dot(input_)
    return pred

In [17]:
wgt = np.array([0.1, 0.2,-.1])

data1 = np.array([8.5, 9.5, 10, 9])
data2 = np.array([0.65, 0.8, 0.8, 0.9])
data3 = np.array([1.2, 1.3, 0.5, 1.0])

x = np.array([data1[0], data2[0], data3[0]])
y = 1.15

α = 0.001
ϵ = 1e-10

for iteration in range(800):
    pred = neural_network(x, wgt)
    error = (pred - y) ** 2
    Δ = pred - y
    
    θs = Δ * x
    
    wgt =wgt - (α * θs)
    
    
    if iteration % 10 == 0:
        print("------------------")
        print("Error: " + str(error) + " Prediction:" + str(pred))
        print("Δ: " + str(Δ))
        print("θs: " + str(θs))
    
    if error < ϵ:
        break

wgt

------------------
Error: 0.0840999999999999 Prediction:0.8600000000000001
Δ: -0.2899999999999998
θs: [ 0.     -0.1885 -0.348 ]
------------------
Error: 0.0810220901006564 Prediction:0.8653562048794029
Δ: -0.284643795120597
θs: [ 0.         -0.18501847 -0.34157255]
------------------
Error: 0.0780568262102127 Prediction:0.8706134824115295
Δ: -0.27938651758847044
θs: [ 0.         -0.18160124 -0.33526382]
------------------
Error: 0.07520008568579237 Prediction:0.8757736597520355
Δ: -0.27422634024796444
θs: [ 0.         -0.17824712 -0.32907161]
------------------
Error: 0.07244789676589009 Prediction:0.8808385303096111
Δ: -0.2691614696903888
θs: [ 0.         -0.17495496 -0.32299376]
------------------
Error: 0.06979643304838296 Prediction:0.8858098543692763
Δ: -0.2641901456307236
θs: [ 0.         -0.17172359 -0.31702817]
------------------
Error: 0.06724200817063647 Prediction:0.8906893597041639
Δ: -0.25931064029583606
θs: [ 0.         -0.16855192 -0.31117277]
------------------
Error: 

array([0.1       , 0.27843019, 0.0447942 ])

array([25.5, 28.5, 30. , 27. ])