In [2]:
import numpy as np

# Simple learning network (Chapter 4-5-)

In [22]:
def neural_network(input_, weight):
    pred = wgt.dot(input_)
    return pred

In [55]:
wgt = np.zeros((3,3))

data1 = np.array([8.5, 9.5, 10, 9])
data2 = np.array([0.65, 0.8, 0.8, 0.9])
data3 = np.array([1.2, 1.3, 0.5, 1.0])

x = np.array([data1[0], data2[0], data3[0]])
y = np.array([1.15, 1., 0.7])

α = 0.02
ϵ = 1e-10

error = np.array([0., 0, 0])
Δ = np.array([0., 0, 0])
              
for iteration in range(10000):
    pred = neural_network(x, wgt)
    
    Δ = pred - y
    
    for i in range(len(y)):
        error[i] = (Δ[i] ** 2)
        
    θs = np.outer(x,Δ)
    
    wgt = wgt - (α * θs)
    
    if iteration % 1000 == 0:
        print("------------------")
        print("Error: " + str(error))
        print("Prediction:" + str(pred))
        print("Δ: " + str(Δ))
        print("θs: " + str(θs))
        print("wgt: " + str(wgt))
    
    #if error.all() < ϵ:
    #    break

wgt

------------------
Error: [1.3225 1.     0.49  ]
Prediction:[0. 0. 0.]
Δ: [-1.15 -1.   -0.7 ]
θs: [[-9.775  -8.5    -5.95  ]
 [-0.7475 -0.65   -0.455 ]
 [-1.38   -1.2    -0.84  ]]
wgt: [[0.1955  0.17    0.119  ]
 [0.01495 0.013   0.0091 ]
 [0.0276  0.024   0.0168 ]]
------------------
Error: [0.02016074 0.81216302 0.26791144]
Prediction:[1.29198853 0.09879912 0.18239838]
Δ: [ 0.14198853 -0.90120088 -0.51760162]
θs: [[ 1.20690251 -7.66020745 -4.39961376]
 [ 0.09229255 -0.58578057 -0.33644105]
 [ 0.17038624 -1.08144105 -0.62112194]]
wgt: [[-24.0140095  153.36868457  88.10118689]
 [ -1.83636543  11.72819353   6.73714959]
 [ -3.39021311  21.65204959  12.43781462]]
------------------
Error: [0.02016074 0.81216302 0.26791144]
Prediction:[1.29198853 0.09879912 0.18239838]
Δ: [ 0.14198853 -0.90120088 -0.51760162]
θs: [[ 1.20690251 -7.66020745 -4.39961376]
 [ 0.09229255 -0.58578057 -0.33644105]
 [ 0.17038624 -1.08144105 -0.62112194]]
wgt: [[-48.15205976 306.57283367 176.09346215]
 [ -3.68221633

array([[-241.2323238 , 1532.0528223 ,  879.94367193],
       [ -18.4471777 ,  117.15698053,   67.28981021],
       [ -34.05632807,  216.28981021,  124.22734192]])

# Basic NN applied to MNIST dataset
Note: For now, it is a 2 layer NN, which is insuficient to have good results

In [59]:
from keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

images = x_train[0:1000]
labels = y_train[0:1000]

wgt = np.zeros((784,10))


for i in range(1000):
    x = images[i]
    y = labels[i]
    
    α = 0.02
    ϵ = 1e-10

    error = np.zeros(10)
    Δ = np.zeros(10)

    for iteration in range(1000):
        pred = neural_network(x, wgt)

        Δ = pred - y

        for k in range(len(y)):
            error[k] = (Δ[k] ** 2)

        θs = np.outer(x,Δ)

        wgt = wgt - (α * θs)

        if iteration % 100 == 0:
            print("------------------")
            print("Error: " + str(error))
            print("Prediction:" + str(pred))
            print("Δ: " + str(Δ))
            print("θs: " + str(θs))
            print("wgt: " + str(wgt))

        #if error.all() < ϵ:
        #    break

wgt

ValueError: shapes (784,10) and (28,28) not aligned: 10 (dim 1) != 28 (dim 0)

In [18]:
X = np.zeros((3,3))
X[2] = np.array([1,2,3.])

In [19]:
X

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 2., 3.]])

In [20]:
X.dot(np.array([1,1,1]))

array([0., 0., 6.])

In [21]:
np.array([1,1,1]).dot(X)

array([1., 2., 3.])

In [34]:
X - np.outer(np.array([1,2,1]),np.array([3,1,4]))

array([[-3., -1., -4.],
       [-6., -2., -8.],
       [-2.,  1., -1.]])

In [47]:
for i in range(3):
    X[i] = i

In [48]:
X

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.]])